// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package team.anthembolts.subsystems;


import team.anthembolts.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import edu.wpi.first.wpilibj.Solenoid;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Actuators extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public Spark liftMotor;
    // private BoltsDoubleSolenoid myDoubleSolenoid;
    private Solenoid myGrabber;
    private Solenoid myPlate;

    private static boolean mGrabberState = false;
    private static boolean mPlateState = true;

    private static  DoubleSolenoid.Value mSolenoidState = DoubleSolenoid.Value.kOff ; 

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public Actuators() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        liftMotor = new Spark(2);
        addChild("LiftMotor",liftMotor);
        liftMotor.setInverted(false);
        
        // myDoubleSolenoid = new BoltsDoubleSolenoid(0, 1, 3, false);
        myGrabber = new Solenoid(0, 1);
        myPlate = new Solenoid(0, 3);

        // addChild("myDoubleSolenoid",myDoubleSolenoid);
        
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
        // myDoubleSolenoid.set(mSolenoidState);
        myGrabber.set( mGrabberState );
        myPlate.set ( mPlateState ) ; 
        

    }

    public static void setSolenoidState(DoubleSolenoid.Value kState) {
        mSolenoidState = kState;
    }

    public static void setGrabber(boolean state) {
        mGrabberState = state;
    }

    public static void setPlate (boolean state) {
        mPlateState = state;
    }

    

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

